services:
  - type: worker
    name: telegram-bot
    env: python
    startCommand: python botonline.py
    envVars:
      - key: BOT_TOKEN
        value: 7504842001:AAHhdabw3BSvOB6MCvV1drdP406cwSi1KCo
      - key: ADMIN_ID
        value: 7828815493
