services:
  - type: web
    name: telegram-bot
    env: python
    startCommand: gunicorn botonine:app  # Falls Datei "botonline.py" heißt
    envVars:
      - key: BOT_TOKEN
        value: dein_token
      - key: ADMIN_ID
        value: deine_admin_id
      - key: WEBHOOK_URL
        value: https://telegram-bot-sk55.onrender.com
